### PR TITLE
fixed a lot of stuff

### LINKED ISSUE #95: implement /users endpoints

### LINKED ISSUE #98: implement /listings endpoints

### LINKED ISSUE #117: add /auth endpoints

### LINKED ISSUE #134: add phone number to user

### PR DESCRIPTION
**Pull request by lukasherz**
I tested it by myself locally - heroku is not tested but I can do so after / before merge. 
But I think most of the stuff should work.
#106 and #107 will be added later.

resolves #95, resolves #98, resolves #117, resolves #134

### CODE REVIEW

File: src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/Utils.java [hunk 1]
```diff
@@ -20,14 +20,44 @@ public static String generateSalt() {
...
+    }
+
+    /**
+     * only allows numbers and a + at the front
+     *
+     * @param str of the phone number
+     * @return the stripped phone number
+     */
+    public static String stripPhoneNumber(String str) {
+        return str.replaceAll("[^+\\d]", "");
```
Comment (matthias-imhof) [inline src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/Utils.java:56]: some phone nr contain -, ()

File: src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/constant/Role.java [hunk 2]
```diff
@@ -52,7 +52,16 @@ public Collection<SimpleGrantedAuthority> generatePermittedAuthoritiesList() {
...
             .collect(java.util.stream.Collectors.toList());
     }
+
+    public boolean isTeam() {
+        return greaterEquals(TEAM);
+    }
+
+    public boolean isUser() {
+        return lessEquals(STUDENT);
+    }
```
Comment (matthias-imhof) [inline src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/constant/Role.java:66]: shouldn't there also be one for ADMIN and INTERNAL?

File: src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/UserController.java [hunk 3]
```diff
@@ -62,34 +74,51 @@ public UserGetDto createUser(@RequestBody UserPostPutDto userPostPutDto) {
     public UserGetDto findUser(@PathVariable UUID id) {
```
Comment (matthias-imhof) [inline src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/UserController.java:74]: Don't we need @AuthenticationPrincipal String authUserId also here, otherwise we would could simply get individual users, no?

File: src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/UserController.java [hunk 4]
```diff
@@ -62,34 +74,51 @@ public UserGetDto createUser(@RequestBody UserPostPutDto userPostPutDto) {
...
-        return UserMapper.INSTANCE.userToUserGetDto(userService.updateUser(user, userInput));
+        User updatedUser = userService.updateUser(userInput, authUser);
+
+        return UserMapper.INSTANCE.userToUserGetDto(updatedUser);
     }
 
     // delete a specific user
     @DeleteMapping("/users/{id}")
     @ResponseStatus(HttpStatus.NO_CONTENT)
     public void deleteUser(@PathVariable UUID id) {
```
Comment (matthias-imhof) [inline src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/UserController.java:113]: same as above?

**Review by matthias-imhof — APPROVED** [review]

File: src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/Utils.java (hunk 1 above)
Comment (lukasherz) [reply src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/Utils.java:56]: but that would be just for representation, not because of the actual phone number. that's why i'm currently dropping it. same for white spaces

File: src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/UserController.java (hunk 3 above)
Comment (lukasherz) [reply src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/UserController.java:74]: that's right. but because i didn't implement the authorization part yet, it's not included yet
